title: "Thomas Samuel Binns, MSci"
author: "Thomas Samuel Binns"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "home.html", title: "Home", icon: home}
  - {file: "CV.html", title: "CV", icon: {['far', 'file-alt']}}
  - {file: "publications.html", title: "Publications", icon: {['far', 'newspaper']}}
  - {file: "links.html", title: "Contact &amp Links"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:t.s.binns@outlook.com"}
  - {title: Twitter, icon: twitter-square, url: "https://twitter.com/TSBinns"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/tsbinns/"}
  - {title: Github, icon: github, url: "https://github.com/tsbinns"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
