title: "Thomas Samuel Binns, M.Sci."
author: ""
description: "Location: London, UK"
permalink: 
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false           # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "https://tsbinns.com", title: "About Me"} #icon: "home"
  - {file: "CV.md", title: "CV", url: "https://tsbinns.com/CV"} #icon: "scroll"
  - {file: "publications.md", title: "Publications", url: "https://tsbinns.com/publications"} #icon: "book"
  - {file: "contact-links.md", title: "Contact &amp Links", url: "https://tsbinns.com/contact-links"} #icon: "address-book"

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Email, icon: "envelope", url: "mailto:t.s.binns@outlook.com"}
  - {title: Scholar, icon: "google", url: "https://scholar.google.co.uk/citations?user=S8yDxUEAAAAJ"}
  - {title: Twitter, icon: "twitter", url: "https://twitter.com/TSBinns"}
  - {title: Github, icon: "github", url: "https://github.com/tsbinns"}
  - {title: LinkedIn, icon: "linkedin", url: "https://www.linkedin.com/in/tsbinns/"}
  - {title: ORCID, icon: "orcid", url: "https://orcid.org/0000-0003-0657-0891"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-seo-tag
